# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import vessel_instructions_pb2 as vessel__instructions__pb2


class VesselInstructionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferInstructions = channel.stream_stream(
                '/vessel_instructions.VesselInstructions/TransferInstructions',
                request_serializer=vessel__instructions__pb2.VesselInstruction.SerializeToString,
                response_deserializer=vessel__instructions__pb2.VesselResult.FromString,
                )


class VesselInstructionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransferInstructions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VesselInstructionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferInstructions': grpc.stream_stream_rpc_method_handler(
                    servicer.TransferInstructions,
                    request_deserializer=vessel__instructions__pb2.VesselInstruction.FromString,
                    response_serializer=vessel__instructions__pb2.VesselResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vessel_instructions.VesselInstructions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VesselInstructions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransferInstructions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/vessel_instructions.VesselInstructions/TransferInstructions',
            vessel__instructions__pb2.VesselInstruction.SerializeToString,
            vessel__instructions__pb2.VesselResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
