# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coin_system.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oin_system.proto\x12\x0b\x63oin_system*?\n\x0bSystemState\x12\x0b\n\x07RUNNING\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0b\n\x07STOPPED\x10\x02\x12\x0b\n\x07WAITING\x10\x03\x42\x45\n+com.han_so1omon.coin_light_show.coin_systemB\x0f\x43oinSystemProtoP\x01\xa2\x02\x02\x43Sb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coin_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.han_so1omon.coin_light_show.coin_systemB\017CoinSystemProtoP\001\242\002\002CS'
  _globals['_SYSTEMSTATE']._serialized_start=34
  _globals['_SYSTEMSTATE']._serialized_end=97
# @@protoc_insertion_point(module_scope)
