# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vessel_instructions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import coin_system_pb2 as coin__system__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19vessel_instructions.proto\x12\x13vessel_instructions\x1a\x11\x63oin_system.proto\"\xb2\x01\n\x11VesselInstruction\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\'\n\x05state\x18\x03 \x01(\x0e\x32\x18.coin_system.SystemState\x12\x31\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32!.vessel_instructions.VesselAction\x12\x10\n\x08strength\x18\x05 \x01(\x05\x12\r\n\x05input\x18\x06 \x01(\t\"X\n\x0cVesselResult\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\'\n\x05state\x18\x02 \x01(\x0e\x32\x18.coin_system.SystemState\x12\x0f\n\x07message\x18\x03 \x01(\t*=\n\x0cVesselAction\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05LIGHT\x10\x01\x12\t\n\x05SOUND\x10\x02\x12\r\n\tVIBRATION\x10\x03\x32}\n\x12VesselInstructions\x12g\n\x14TransferInstructions\x12&.vessel_instructions.VesselInstruction\x1a!.vessel_instructions.VesselResult\"\x00(\x01\x30\x01\x42U\n3com.han_so1omon.coin_light_show.vessel_instructionsB\x17VesselInstructionsProtoP\x01\xa2\x02\x02VIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vessel_instructions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n3com.han_so1omon.coin_light_show.vessel_instructionsB\027VesselInstructionsProtoP\001\242\002\002VI'
  _globals['_VESSELACTION']._serialized_start=340
  _globals['_VESSELACTION']._serialized_end=401
  _globals['_VESSELINSTRUCTION']._serialized_start=70
  _globals['_VESSELINSTRUCTION']._serialized_end=248
  _globals['_VESSELRESULT']._serialized_start=250
  _globals['_VESSELRESULT']._serialized_end=338
  _globals['_VESSELINSTRUCTIONS']._serialized_start=403
  _globals['_VESSELINSTRUCTIONS']._serialized_end=528
# @@protoc_insertion_point(module_scope)
