# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: witch_intuitions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import coin_system_pb2 as coin__system__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16witch_intuitions.proto\x12\x10witch_intuitions\x1a\x11\x63oin_system.proto\"n\n\x10IntuitionRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\'\n\x05state\x18\x03 \x01(\x0e\x32\x18.coin_system.SystemState\x12\x0f\n\x07message\x18\x04 \x01(\t\"\xde\x01\n\x11IntuitionResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\'\n\x05state\x18\x03 \x01(\x0e\x32\x18.coin_system.SystemState\x12\x39\n\nexpression\x18\x04 \x01(\x0e\x32%.witch_intuitions.IntuitiveExpression\x12\x31\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32!.witch_intuitions.IntuitiveAction\x12\x10\n\x08strength\x18\x06 \x01(\x05*O\n\x13IntuitiveExpression\x12\t\n\x05\x42LANK\x10\x00\x12\t\n\x05HAPPY\x10\x01\x12\x07\n\x03SAD\x10\x02\x12\x0b\n\x07\x41NNOYED\x10\x03\x12\x0c\n\x08\x43ONFUSED\x10\x04*@\n\x0fIntuitiveAction\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05LIGHT\x10\x01\x12\t\n\x05SOUND\x10\x02\x12\r\n\tVIBRATION\x10\x03\x32v\n\x0fWitchIntuitions\x12\x63\n\x12TransferIntuitions\x12\".witch_intuitions.IntuitionRequest\x1a#.witch_intuitions.IntuitionResponse\"\x00(\x01\x30\x01\x42O\n0com.han_so1omon.coin_light_show.witch_intuitionsB\x14WitchIntuitionsProtoP\x01\xa2\x02\x02WIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'witch_intuitions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0com.han_so1omon.coin_light_show.witch_intuitionsB\024WitchIntuitionsProtoP\001\242\002\002WI'
  _globals['_INTUITIVEEXPRESSION']._serialized_start=400
  _globals['_INTUITIVEEXPRESSION']._serialized_end=479
  _globals['_INTUITIVEACTION']._serialized_start=481
  _globals['_INTUITIVEACTION']._serialized_end=545
  _globals['_INTUITIONREQUEST']._serialized_start=63
  _globals['_INTUITIONREQUEST']._serialized_end=173
  _globals['_INTUITIONRESPONSE']._serialized_start=176
  _globals['_INTUITIONRESPONSE']._serialized_end=398
  _globals['_WITCHINTUITIONS']._serialized_start=547
  _globals['_WITCHINTUITIONS']._serialized_end=665
# @@protoc_insertion_point(module_scope)
