# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import witch_intuitions_pb2 as witch__intuitions__pb2


class WitchIntuitionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferIntuitions = channel.stream_stream(
                '/witch_intuitions.WitchIntuitions/TransferIntuitions',
                request_serializer=witch__intuitions__pb2.IntuitionRequest.SerializeToString,
                response_deserializer=witch__intuitions__pb2.IntuitionResponse.FromString,
                )


class WitchIntuitionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransferIntuitions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WitchIntuitionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferIntuitions': grpc.stream_stream_rpc_method_handler(
                    servicer.TransferIntuitions,
                    request_deserializer=witch__intuitions__pb2.IntuitionRequest.FromString,
                    response_serializer=witch__intuitions__pb2.IntuitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'witch_intuitions.WitchIntuitions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WitchIntuitions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransferIntuitions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/witch_intuitions.WitchIntuitions/TransferIntuitions',
            witch__intuitions__pb2.IntuitionRequest.SerializeToString,
            witch__intuitions__pb2.IntuitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
